---
- name: Converge
  hosts: all
  vars:
    ssl_directories:
      - path: "/etc/ssl/certs"
        owner: root
        group: root
        mode: "u=rwx,go=rx"
      - path: "/etc/ssl/private"
        owner: root
        group: root
        mode: "u=rwx,go=rx"
    ssl_files:
      - src: "{{ playbook_dir }}/certs/www.example.com.crt"
        dest: "/etc/ssl/certs/www.example.com.crt"
        owner: root
        group: root
        mode: "u=rw,go=r"
      - src: "{{ playbook_dir }}/certs/www.example.com.key"
        dest: "/etc/ssl/private/www.example.com.key"
        owner: root
        group: root
        mode: "u=rw,go="
  roles:
    - role: ansible-role-ssl
